name: Automatic Builds

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install libdragon
      run: npm install -g libdragon
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        libdragon init
        libdragon make -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: sodium64
        path: |
          sodium64.z64
          rom-converter.py

  update-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get artifacts
      uses: actions/download-artifact@v4
    - name: Package artifacts
      run: |
        mv sodium64/sodium64.z64 .
        mv sodium64/rom-converter.py .
        zip -r sodium64.zip sodium64.z64 rom-converter.py
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        name: Rolling Release
        body: These are automatically updated builds of the latest commit.
        artifacts: sodium64.zip
        tag: release
        token: ${{ secrets.GITHUB_TOKEN }}
